import { Fira_Code } from "next/font/google";
import "./globals.css";

import Header from "@/widgets/site/header";
import Footer from "@/widgets/site/footer";

const firaCode = Fira_Code({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={firaCode.className}>
        <Header />

        {children}

        <Footer />
      </body>
    </html>
  );
}
